# -*- coding: utf-8 -*-
"""dl_assign1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp4c-x-l-huh0HJfhoHJIIErW96kTEKw
"""

import tensorflow as tf
import matplotlib.pyplot as plt

(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()

train_images = train_images /255.0
test_images = test_images / 255.0

print(train_images.shape)
print(test_images.shape)
print(train_labels)

plt.imshow(train_images[11], cmap='gray')
plt.show()

# Defining neural network model
my_model = tf.keras.models.Sequential()
my_model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))
my_model.add(tf.keras.layers.Dense(128, activation='relu'))     #Rectified Linear Unit        #Dense layers are used to learn complex patterns in data.
my_model.add(tf.keras.layers.Dense(10, activation='softmax'))   #softmax is often used as the activation function in the output layer for classification tasks

# Compiling the model
my_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) #Adaptive Moment Estimation #sparse_categorical_crossentropy for multi-class classification

# Training the model
my_model.fit(train_images, train_labels, epochs=3)

val_loss, val_acc = my_model.evaluate(test_images, test_labels)
print('Test accuracy: ', val_acc)

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
import numpy as np

# Saving the model
my_model.save('my_mnist_model.keras')

from tensorflow.keras.datasets import fashion_mnist
# Load the dataset
(trainX, trainy), (testX, testy) = fashion_mnist.load_data()
# Print dataset dimensions
# print(f"Training data shape: {trainX.shape}, Labels: {trainy.shape}")
# print(f"Testing data shape: {testX.shape}, Labels: {testy.shape}")
print(trainX.shape)
print(testX.shape)
print(trainy)

plt.imshow(trainX[6], cmap='gray')
plt.show()

trainX = trainX /255.0
testX = testX / 255.0

# Defining neural network model
my_model = tf.keras.models.Sequential()
my_model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))
my_model.add(tf.keras.layers.Dense(128, activation='relu'))     #Rectified Linear Unit        #Dense layers are used to learn complex patterns in data.
my_model.add(tf.keras.layers.Dense(10, activation='softmax'))   #softmax is often used as the activation function in the output layer for classification tasks

# Compiling the model
my_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) #Adaptive Moment Estimation #sparse_categorical_crossentropy for multi-class classification

# Training the model
my_model.fit(trainX, trainy, epochs=3)

val_loss, val_acc = my_model.evaluate(testX, testy)
print('Test accuracy: ', val_acc)