# -*- coding: utf-8 -*-
"""assign7_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwVOe312cxnZat1naRV5H1gxYVAp25Ry
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16, ResNet50

import os

if "flower_photos" in os.listdir(dataset_path):
    dataset_path = os.path.join(dataset_path, "flower_photos")

print("Final dataset path:", dataset_path)
print("Classes:", os.listdir(dataset_path))

import tensorflow as tf

IMG_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 123

train_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_path,
    validation_split=0.2,
    subset="training",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="int"
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_path,
    validation_split=0.2,
    subset="validation",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="int"
)

class_names = train_ds.class_names
num_classes = len(class_names)

print("Class names:", class_names)
print("Number of classes:", num_classes)

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(AUTOTUNE)
val_ds = val_ds.prefetch(AUTOTUNE)

from tensorflow.keras import layers, models

vgg_model = models.Sequential([
    layers.Input(shape=(224, 224, 3)),
    layers.Rescaling(1./255),
    vgg_base,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(num_classes, activation="softmax")
])

print("Number of classes:", num_classes)
print("Model output shape:", vgg_model.output_shape)

vgg_model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

vgg_history = vgg_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=1
)

vgg_history = vgg_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5,
    initial_epoch=1
)

vgg_loss, vgg_accuracy = vgg_model.evaluate(val_ds)

print("VGG16 Validation Loss:", vgg_loss)
print("VGG16 Validation Accuracy:", vgg_accuracy)

plt.figure(figsize=(8, 5))

plt.plot(
    vgg_history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    vgg_history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("VGG16 Training and Validation Accuracy")
plt.legend()
plt.show()